---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен хранить данные о посещениях пользователей, чтобы при следующем входе предлагать продолжить покупки
  - Поддержка международных и локальных платежных систем
  - Функция линии поддержки покупатлей, возмодность возврата товаров
  - Кнопки оформить заказ, добавить в корзину яркого цвета красного алого, привлекательного
  - При регистрации и входе пароль закрывать звездочками, кнопка войти и зарегистрироваться яркого цвета красного 
  - Сайт должен соответствовать нормам законодательства РФ
  - При продаже алкоголя, табака и др спрашивать возраст пользователя, Изображения товаров для взрослых заблюрить, открыть если есть 18 лет
   
  
